### PR TITLE
Add a new option to expand hidden lines

### PR DESCRIPTION
**Pull request by stefanbauer**
If you select specific lines to show, until now only these files are shown and the others are removed from the gist. With this PR, you have a new option, you could set. `data-gist-lines-expanded="true"`. If you set this option, the other lines are not removed entirely, they are just hidden and shown as collapsed. A new icon was added with a little bit of meta data to expand these lines.

I need it for one of my projects, so feel free to merge or not ;) It is just a quick implementation. My CS Fixer fixed also unfortunately some cs stuff in that commit that did notice first. Sorry for that.

Here is a screenshot from the updated examples page.

screen shot 2018-01-18 at 06 53 22

If this PR is merged, this solves #60

### CODE REVIEW

**Comment by stefanbauer** [comment]
Yeah i tried that first tbh, but i found no unicode character that does look good. That's why for now i used a svg. I am also not so much happy with that inline css. But as said, it was quick implementation. Maybe i find some more time to improve it. Thanks for merging.

**Comment by stefanbauer** [comment]
May be the version should be bumped up and added in the change log? What do you think? Or what is the version convention @blairvanderhoof ?

**Comment by blairvanderhoof** [comment]
@stefanbauer feel free to bump it per convention (2.7).  Also feel free to update the changelog.

For the website for gist-embed that has the examples, we need to update https://github.com/blairvanderhoof/gist-embed/tree/gh-pages BUT, it depends on cdnjs being updated with the new code.  We would need to minify the new js then submit a pull request to cdnjs to create a new version of gist-embed.  If you have the bandwidth to do this, that would be amazing.

**Comment by stefanbauer** [comment]
@blairvanderhoof as i know, i can not tag it as a contributor. So you have to do it. I'll update the changelog. Already updated the minified version. Checked cdnjs some min. ago.. That would take a long time as i see, until they update it :(

**Comment by stefanbauer** [comment]
sorry, just saw autoupdate is enabled. So it should be automatically updated?

**Comment by blairvanderhoof** [comment]
I just tagged 2.7.0. Would you like to update the README? Also keep an eye
out for when 2.7.0 is autoenabled by cdnjs, you can update the gh-pages
index.html. Thanks agian.

**Pull request merged**
